### ISSUE TITLE
current encapsulation issues

### ISSUE THREAD

**Issue by cmalk** [project415x/project415x.github.io#86]
This code is looking sweet, but it can get sweeter:
- in canvas.js under the comment // add drag functionality to vector: I feel that Sauron should be doing this. only Sauron should know that the input canvas is where the vector gets clicked and dragged, and the output canvas is where the targets are being drawn. Because, during tutorial mode, these might not happen!

Also:
- the functions that draw targets should be relocated to target.js
- Sauron should be the one picking how to randomize the targets, because his scheme will change in level 2 (he is devious)

**Comment by SkamDart** [comment]
Hey Cary,

So we actually aren't attaching a listener to the vector, we are faking as if there is. In `Canvas.prototype.drawCanvas` we have the following lines.
**Note** this comment is misleading. We actually don't have a listener on the vector. It is associated with the canvas.

```
  // add drag functionality to vector
  if(this.type === "input") {
    this.getCanvas().call(this.vectorDrag());
  } 
};
```

Here is where we are adding an event listener to the canvas which is `Canvas.prototype.vectorDrag`.
**Note**: `self = this` is used to differentiate between our canvas object and the d3 object
Without `this`, `self.getD()` throws an error because the d3 object does not have a `getD()` function.

```
Canvas.prototype.vectorDrag = function() {
  self = this;
  return d3.behavior.drag()
              .on("dragstart", function (){
                Sauron.tellSauron(self.getD());
              })
              .on("drag", function() {
                Sauron.tellSauron(self.getD());
              });
};
```

This essentially says 'tell sauron the location of the vector' whether we click on the vector itself and drag it, or click on the canvas and it automatically updates the vector to that point.

**Comment by cmalk** [comment]
OK... I don't fully get that but I'll ask you about it in person later.

A separate encapsulation issue is that the screen coordinate information should be located in the instance of the Canvas object. Right now they're hard-coded in utils/math.js. While this is less of a priority than getting levels 1-3 up and running, eventually this should be migrated over to canvas.js, and encapsulated enough that the canvases can be set to a different sizes. (That'll be necessary for making the canvas size change when the game is played on a tablet.)
